/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mijwvkigfdvdanqbqahy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pand2a2lnZmR2ZGFucWJxYWh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE2NzczMDAsImV4cCI6MjA3NzI1MzMwMH0.dGDSv5Tm4qSXNWBb7g0QchChy-KlQBe5p1S-4UCpQS4"